% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Jan-2021 21:18:09
%  MATLAB version: 9.9.0.1538559 (R2020b) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('cell1sectorwmt.mat');

Mwtc1 = saveVarsMat.Mwtc1; % <100001x20 double> too many elements

clear saveVarsMat;
